/* eslint-disable */
import { FuseNavigationItem } from "@fuse/components/navigation";
import {
  getRolesWithFeature,
  NAV_ITEM_FEATURE,
} from "app/core/auth/role-permissions";

const metaFor = (id: keyof typeof NAV_ITEM_FEATURE) => ({
  allowedRoles: getRolesWithFeature(NAV_ITEM_FEATURE[id]),
});

export const defaultNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
    meta: metaFor("dashboard"),
  },
  {
    id: "reports",
    title: "Reports",
    type: "basic",
    icon: "heroicons_outline:chart-bar",
    link: "/secure/reports",
    meta: metaFor("reports"),
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  meta: metaFor("scan"),
  },
  {
    id: "parcels-history",
    title: "Parcels",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
    meta: metaFor("parcels-history"),
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "heroicons_outline:users",
    link: "/secure/customers",
    meta: metaFor("customers"),
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "heroicons_outline:map",
    link: "/secure/routes",
    meta: metaFor("routes"),
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "heroicons_outline:map-pin",
    link: "/secure/destinations",
    meta: metaFor("destinations"),
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
    meta: metaFor("trips"),
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
    meta: metaFor("drivers"),
  },
  {
    id: "siders",
    title: "Siders",
    type: "basic",
    icon: "heroicons_outline:users",
    link: "/secure/siders",
    meta: metaFor("siders"),
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
    meta: metaFor("trucks"),
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
    meta: metaFor("complaints"),
  },
  {
    id: "users",
    title: "Users",
    type: "basic",
    icon: "heroicons_outline:user-group",
    link: "/secure/users",
    meta: {
      allowedRoles: ["managing-director"],
    },
  },
];
export const compactNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
    meta: metaFor("dashboard"),
  },
  {
    id: "reports",
    title: "Reports",
    type: "basic",
    icon: "heroicons_outline:chart-bar",
    link: "/secure/reports",
    meta: metaFor("reports"),
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  meta: metaFor("scan"),
  },
  {
    id: "parcels-history",
    title: "Parcels",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
    meta: metaFor("parcels-history"),
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
    meta: metaFor("customers"),
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
    meta: metaFor("routes"),
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
    meta: metaFor("destinations"),
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
    meta: metaFor("trips"),
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
    meta: metaFor("drivers"),
  },
  {
    id: "siders",
    title: "Siders",
    type: "basic",
    icon: "heroicons_outline:users",
    link: "/secure/siders",
    meta: metaFor("siders"),
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
    meta: metaFor("trucks"),
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
    meta: metaFor("complaints"),
  },
];
export const futuristicNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
    meta: metaFor("dashboard"),
  },
  {
    id: "reports",
    title: "Reports",
    type: "basic",
    icon: "heroicons_outline:chart-bar",
    link: "/secure/reports",
    meta: metaFor("reports"),
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  meta: metaFor("scan"),
  },
  {
    id: "parcels-history",
    title: "Parcels",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
    meta: metaFor("parcels-history"),
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
    meta: metaFor("customers"),
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
    meta: metaFor("routes"),
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
    meta: metaFor("destinations"),
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
    meta: metaFor("trips"),
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
    meta: metaFor("drivers"),
  },
  {
    id: "siders",
    title: "Siders",
    type: "basic",
    icon: "heroicons_outline:users",
    link: "/secure/siders",
    meta: metaFor("siders"),
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
    meta: metaFor("trucks"),
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
    meta: metaFor("complaints"),
  },
];
export const horizontalNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
    meta: metaFor("dashboard"),
  },
  {
    id: "reports",
    title: "Reports",
    type: "basic",
    icon: "heroicons_outline:chart-bar",
    link: "/secure/reports",
    meta: metaFor("reports"),
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  meta: metaFor("scan"),
  },
  {
    id: "parcels-history",
    title: "Parcels",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
    meta: metaFor("parcels-history"),
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
    meta: metaFor("customers"),
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
    meta: metaFor("routes"),
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
    meta: metaFor("destinations"),
  },
];
