/* eslint-disable */
import { FuseNavigationItem } from "@fuse/components/navigation";

export const defaultNavigation: FuseNavigationItem[] = [
    {
        id   : 'dashboard',
        title: 'Dashboard',
        type : 'basic',
    icon : 'custom:dashboard',
        link : '/secure/dashboard',
    },
    {
        id   : 'parcels-history',
        title: 'Parcels History',
        type : 'basic',
    icon : 'custom:parcels-history',
        link : '/secure/parcels-history',
    },
    {
        id   : 'live-tracking',
        title: 'Live Tracking',
        type : 'basic',
    icon : 'custom:live-tracking',
        link : '/secure/live-tracking',
    },
    {
        id   : 'revenue',
        title: 'Revenue',
        type : 'basic',
    icon : 'custom:revenue',
        link : '/secure/revenue',
    },
    {
        id   : 'customers',
        title: 'Customers',
        type : 'basic',
    icon : 'custom:customers',
        link : '/secure/customers',
    },
    {
        id   : 'destinations',
        title: 'Destinations',
        type : 'basic',
    icon : 'custom:destinations',
        link : '/secure/destinations',
    },
    {
        id   : 'parcels',
        title: 'Parcels',
        type : 'basic',
    icon : 'custom:parcels',
        link : '/secure/parcels',
    },
    {
        id   : 'routes',
        title: 'Routes',
        type : 'basic',
    icon : 'custom:routes',
        link : '/secure/routes',
    },
];
export const compactNavigation: FuseNavigationItem[] = [
    {
        id   : 'dashboard',
        title: 'Dashboard',
        type : 'basic',
    icon : 'custom:dashboard',
        link : '/secure/dashboard',
    },
    {
        id   : 'parcels-history',
        title: 'Parcels History',
        type : 'basic',
    icon : 'custom:parcels-history',
        link : '/secure/parcels-history',
    },
    {
        id   : 'live-tracking',
        title: 'Live Tracking',
        type : 'basic',
    icon : 'custom:live-tracking',
        link : '/secure/live-tracking',
    },
    {
        id   : 'revenue',
        title: 'Revenue',
        type : 'basic',
    icon : 'custom:revenue',
        link : '/secure/revenue',
    },
    {
        id   : 'customers',
        title: 'Customers',
        type : 'basic',
    icon : 'custom:customers',
        link : '/secure/customers',
    },
    {
        id   : 'destinations',
        title: 'Destinations',
        type : 'basic',
    icon : 'custom:destinations',
        link : '/secure/destinations',
    },
    {
        id   : 'parcels',
        title: 'Parcels',
        type : 'basic',
    icon : 'custom:parcels',
        link : '/secure/parcels',
    },
    {
        id   : 'routes',
        title: 'Routes',
        type : 'basic',
    icon : 'custom:routes',
        link : '/secure/routes',
    },
];
export const futuristicNavigation: FuseNavigationItem[] = [
    {
        id   : 'dashboard',
        title: 'Dashboard',
        type : 'basic',
    icon : 'custom:dashboard',
        link : '/secure/dashboard',
    },
    {
        id   : 'parcels-history',
        title: 'Parcels History',
        type : 'basic',
    icon : 'custom:parcels-history',
        link : '/secure/parcels-history',
    },
    {
        id   : 'live-tracking',
        title: 'Live Tracking',
        type : 'basic',
    icon : 'custom:live-tracking',
        link : '/secure/live-tracking',
    },
    {
        id   : 'revenue',
        title: 'Revenue',
        type : 'basic',
    icon : 'custom:revenue',
        link : '/secure/revenue',
    },
    {
        id   : 'customers',
        title: 'Customers',
        type : 'basic',
    icon : 'custom:customers',
        link : '/secure/customers',
    },
    {
        id   : 'destinations',
        title: 'Destinations',
        type : 'basic',
    icon : 'custom:destinations',
        link : '/secure/destinations',
    },
    {
        id   : 'parcels',
        title: 'Parcels',
        type : 'basic',
    icon : 'custom:parcels',
        link : '/secure/parcels',
    },
    {
        id   : 'routes',
        title: 'Routes',
        type : 'basic',
    icon : 'custom:routes',
        link : '/secure/routes',
    },
];
export const horizontalNavigation: FuseNavigationItem[] = [
    {
        id   : 'dashboard',
        title: 'Dashboard',
        type : 'basic',
    icon : 'custom:dashboard',
        link : '/secure/dashboard',
    },
    {
        id   : 'parcels-history',
        title: 'Parcels History',
        type : 'basic',
    icon : 'custom:parcels-history',
        link : '/secure/parcels-history',
    },
    {
        id   : 'live-tracking',
        title: 'Live Tracking',
        type : 'basic',
    icon : 'custom:live-tracking',
        link : '/secure/live-tracking',
    },
    {
        id   : 'revenue',
        title: 'Revenue',
        type : 'basic',
    icon : 'custom:revenue',
        link : '/secure/revenue',
    },
    {
        id   : 'customers',
        title: 'Customers',
        type : 'basic',
    icon : 'custom:customers',
        link : '/secure/customers',
    },
    {
        id   : 'destinations',
        title: 'Destinations',
        type : 'basic',
    icon : 'custom:destinations',
        link : '/secure/destinations',
    },
    {
        id   : 'parcels',
        title: 'Parcels',
        type : 'basic',
    icon : 'custom:parcels',
        link : '/secure/parcels',
    },
    {
        id   : 'routes',
        title: 'Routes',
        type : 'basic',
    icon : 'custom:routes',
        link : '/secure/routes',
    },
];
