/* eslint-disable */
import { FuseNavigationItem } from "@fuse/components/navigation";

export const defaultNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  },
  {
    id: "parcels-history",
    title: "Parcels History",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "heroicons_outline:users",
    link: "/secure/customers",
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "heroicons_outline:map",
    link: "/secure/routes",
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "heroicons_outline:map-pin",
    link: "/secure/destinations",
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
  },
];
export const compactNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  },
  {
    id: "parcels-history",
    title: "Parcels History",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
  },
];
export const futuristicNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  },
  {
    id: "parcels-history",
    title: "Parcels History",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
  },
  {
    id: "trips",
    title: "Trips",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trips",
  },
  {
    id: "drivers",
    title: "Drivers",
    type: "basic",
    icon: "heroicons_outline:identification",
    link: "/secure/drivers",
  },
  {
    id: "trucks",
    title: "Trucks",
    type: "basic",
    icon: "heroicons_outline:truck",
    link: "/secure/trucks",
  },
  {
    id: "complaints",
    title: "Complaints",
    type: "basic",
    icon: "heroicons_outline:exclamation-triangle",
    link: "/secure/complaints",
  },
];
export const horizontalNavigation: FuseNavigationItem[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    type: "basic",
    icon: "custom:dashboard",
    link: "/secure/dashboard",
  },
  {
  id: "scan",
  title: "Scan",
  type: "basic",
  icon: "heroicons_outline:qr-code",
  link: "/secure/scanning",
  },
  {
    id: "parcels-history",
    title: "Parcels History",
    type: "basic",
    icon: "custom:parcels-history",
    link: "/secure/parcels",
  },
  {
    id: "customers",
    title: "Customers",
    type: "basic",
    icon: "custom:customers",
    link: "/secure/customers",
  },
  {
    id: "routes",
    title: "Routes",
    type: "basic",
    icon: "custom:routes",
    link: "/secure/routes",
  },
  {
    id: "destinations",
    title: "Offices",
    type: "basic",
    icon: "custom:destinations",
    link: "/secure/destinations",
  },
];
